//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int Id { get; set; }
        public int TaskId { get; set; }
        public byte[] Value { get; set; }
        public int TypeId { get; set; }
    
        public virtual AttachmentType AttachmentType { get; set; }
        public virtual Task Task { get; set; }
    }
}
